#  ____  __  __  __  __  ____ 
# (  _ \(  )(  )(  \/  )(  _ \
#  ) _ < )(__)(  )    (  )___/
# (____/(______)(_/\/\_)(__)
#
# https://github.com/launchfirestorm/bump

prefix = "v"

# NOTE: some fields are modified by bump
#   - mode: "semver" or "calver"
#   - minor|patch: optional, can be removed if not needed
[base]
mode = "semver"
delimiter = "."
major = 0
minor = 1
patch = 0

[phase]
separator = "-"
name = ""
delimiter = "."
distance = 0

# suffix type:
#  - "git_sha"  : append 7 char sha1 of the current commit (default)
#  - "branch"   : append the current git branch name
[suffix]
mode = "git_sha"
separator = "+"

[timestamp]
format = "%Y-%m-%d %H:%M:%S %Z"
last = "{timestamp}"

# printed label: shown but never tracked, useful injecting dynamic values
#  - position: "before-prefix", "after-prefix",
#              "before-base", "after-base",
#              "before-phase", "after-phase",
[label]
position = "after-base"
