/** This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

#ifndef BUMP_VERSION_H
#define BUMP_VERSION_H

#define VERSION_PREFIX "{prefix}"
#define VERSION_MAJOR {major}
#define VERSION_MINOR {minor}
#define VERSION_PATCH {patch}
#define VERSION_PHASE "{phase}"
#define VERSION_STRING "{version_string}"
#define VERSION_TIMESTAMP "{timestamp}"

#endif /* BUMP_VERSION_H */
