// This file is generated by:
//  ____  __  __  __  __  ____ 
// (  _ \(  )(  )(  \/  )(  _ \
//  ) _ < )(__)(  )    (  )___/
// (____/(______)(_/\/\_)(__)  
//
// https://github.com/launchfirestorm/bump

package version

const (
	PREFIX    = "{prefix}"
	MAJOR     = {major}
	MINOR     = {minor}
	PATCH     = {patch}
	PHASE     = "{phase}"
	STRING    = "{version_string}"
    TIMESTAMP = "{timestamp}"
)
