/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public class Version {
    public static final String STRING = "{version_string}";
    public static final String TIMESTAMP = "{timestamp}";
}
