/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public class Version {
    public static final String PREFIX = "{prefix}";
    public static final int MAJOR = {major};
    public static final int MINOR = {minor};
    public static final int PATCH = {patch};
    public static final String PHASE = "{phase}";
    public static final String STRING = "{version_string}";
    public static final String TIMESTAMP = "{timestamp}";
}
