# This file is generated by:
 #  ____  __  __  __  __  ____ 
 # (  _ \(  )(  )(  \/  )(  _ \
 #  ) _ < )(__)(  )    (  )___/
 # (____/(______)(_/\/\_)(__)  
 #
 # https://github.com/launchfirestorm/bump
 #/

VERSION_STRING = "{version_string}"
VERSION_TIMESTAMP = "{timestamp}"
