use crate::{bump::BumpError, version::{Version, VersionType}};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Copy)]
pub enum Language {
    C,
    Go,
    Java,
    CSharp,
    Python,
}

impl Language {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "c" => Some(Language::C),
            "go" => Some(Language::Go),
            "java" => Some(Language::Java),
            "csharp" => Some(Language::CSharp),
            "python" => Some(Language::Python),
            _ => None,
        }
    }

    fn file_description(self) -> &'static str {
        match self {
            Language::C => "C header file",
            Language::Go => "Go source file",
            Language::Java => "Java source file",
            Language::CSharp => "C# source file",
            Language::Python => "Python source file",
        }
    }

}

fn optional_timestamp_line(lang: Language, version: &Version) -> String {
    if let Ok(timestamp) = version.get_timestamp()  {
        match lang {
            Language::C => format!("#define VERSION_TIMESTAMP \"{}\"\n", timestamp),
            Language::Go => format!("\tTIMESTAMP = \"{}\"\n", timestamp),
            Language::Java => format!("    public static final String TIMESTAMP = \"{}\";\n", timestamp),
            Language::CSharp => format!("    public const string TIMESTAMP = \"{}\";\n", timestamp),
            Language::Python => format!("VERSION_TIMESTAMP = \"{}\"\n", timestamp),
        }
    } else {
        String::new()
    }
}

fn write_output(lang: Language, path: &Path, content: String) -> Result<(), BumpError> {
    fs::write(path, content).map_err(BumpError::IoError)?;
    println!("{} written to {}", lang.file_description(), path.display());
    Ok(())
}

fn c_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let version_string = version.to_string()?;
    
    let content = match &version.version_type {
        VersionType::CalVer { .. } => {
            // CalVer: only output VERSION_STRING
            format!(
                r#"/** This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

#ifndef BUMP_VERSION_H
#define BUMP_VERSION_H

#define VERSION_STRING "{}"

#endif /* BUMP_VERSION_H */
"#,
                version_string
            )
        }
        VersionType::SemVer ( semver ) => {
            // SemVer: output all fields
            format!(
                r#"/** This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

#ifndef BUMP_VERSION_H
#define BUMP_VERSION_H

#define VERSION_PREFIX "{}"
#define VERSION_MAJOR {}
#define VERSION_MINOR {}
#define VERSION_PATCH {}
#define VERSION_CANDIDATE {}
#define VERSION_STRING "{}"
{}

#endif /* BUMP_VERSION_H */
"#,
                semver.format.prefix,
                semver.version.major,
                semver.version.minor,
                semver.version.patch,
                semver.version.candidate,
                version_string,
                optional_timestamp_line(Language::C, version)
            )
        }
    };

    write_output(Language::C, path, content)
}

fn go_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let version_string = version.to_string()?;
    let content = match &version.version_type {
        VersionType::CalVer { .. } => {
            // CalVer: only output STRING
            format!(
                r#"// This file is generated by:
//  ____  __  __  __  __  ____ 
// (  _ \(  )(  )(  \/  )(  _ \
//  ) _ < )(__)(  )    (  )___/
// (____/(______)(_/\/\_)(__)  
//
// https://github.com/launchfirestorm/bump

package version

const (
	STRING = "{}"
)
"#,
                version_string
            )
        }
        VersionType::SemVer ( semver ) => {
            // SemVer: output all fields
            format!(
                r#"// This file is generated by:
//  ____  __  __  __  __  ____ 
// (  _ \(  )(  )(  \/  )(  _ \
//  ) _ < )(__)(  )    (  )___/
// (____/(______)(_/\/\_)(__)  
//
// https://github.com/launchfirestorm/bump

package version

const (
	PREFIX    = "{}"
	MAJOR     = {}
	MINOR     = {}
	PATCH     = {}
	CANDIDATE = {}
	STRING    = "{}"
    "{}"
)
"#,
                semver.format.prefix,
                semver.version.major,
                semver.version.minor,
                semver.version.patch,
                semver.version.candidate,
                version_string,
                optional_timestamp_line(Language::Go, version),
            )
        }
    };

    write_output(Language::Go, path, content)
}

fn java_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let version_string = version.to_string()?;
    
    let content = match &version.version_type {
        VersionType::CalVer { .. } => {
            // CalVer: only output STRING
            format!(
                r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public class Version {{
    public static final String STRING = "{}";
}}
"#,
                version_string
            )
        }
        VersionType::SemVer ( semver ) => {
            // SemVer: output all fields
            format!(
                r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public class Version {{
    public static final String PREFIX = "{}";
    public static final int MAJOR = {};
    public static final int MINOR = {};
    public static final int PATCH = {};
    public static final int CANDIDATE = {};
    public static final String STRING = "{}";
    {}
}}
"#,
                semver.format.prefix,
                semver.version.major,
                semver.version.minor,
                semver.version.patch,
                semver.version.candidate,
                version_string,
                optional_timestamp_line(Language::Java, version)
            )
        }
    };

    write_output(Language::Java, path, content)
}

fn csharp_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let version_string = version.to_string()?;
    
    let content = match &version.version_type {
        VersionType::CalVer { .. } => {
            // CalVer: only output STRING
            format!(
                r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public static class Version {{
    public const string STRING = "{}";
}}
"#,
                version_string
            )
        }
        VersionType::SemVer ( semver ) => {
            // SemVer: output all fields
            format!(
                r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public static class Version {{
    public const string PREFIX = "{}";
    public const int MAJOR = {};
    public const int MINOR = {};
    public const int PATCH = {};
    public const int CANDIDATE = {};
    public const string STRING = "{}";
    {}
}}
"#,
                semver.format.prefix,
                semver.version.major,
                semver.version.minor,
                semver.version.patch,
                semver.version.candidate,
                version_string,
                optional_timestamp_line(Language::CSharp, version)
            )
        }
    };

    write_output(Language::CSharp, path, content)
}

fn python_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let version_string = version.to_string()?;
    
    let content = match &version.version_type {
        VersionType::CalVer { .. } => {
            // CalVer: only output STRING
            format!(
                r#"# This file is generated by:
 #  ____  __  __  __  __  ____ 
 # (  _ \(  )(  )(  \/  )(  _ \
 #  ) _ < )(__)(  )    (  )___/
 # (____/(______)(_/\/\_)(__)  
 #
 # https://github.com/launchfirestorm/bump
 #/

VERSION_STRING = "{}"
"#,
                version_string
            )
        }
        VersionType::SemVer ( semver ) => {
            // SemVer: output all fields
            format!(
                r#"# This file is generated by:
 #  ____  __  __  __  __  ____ 
 # (  _ \(  )(  )(  \/  )(  _ \
 #  ) _ < )(__)(  )    (  )___/
 # (____/(______)(_/\/\_)(__)  
 #
 # https://github.com/launchfirestorm/bump
 #/

VERSION_PREFIX = "{}"
VERSION_MAJOR = {}
VERSION_MINOR = {}
VERSION_PATCH = {}
VERSION_CANDIDATE = {}
VERSION_STRING = "{}"
{}
"#,
                semver.format.prefix,
                semver.version.major,
                semver.version.minor,
                semver.version.patch,
                semver.version.candidate,
                version_string,
                optional_timestamp_line(Language::Python, version)
            )
        }
    };

    write_output(Language::Python, path, content)
}


pub fn output_file(
    lang: &Language,
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    match lang {
        Language::C => c_output(version, path),
        Language::Go => go_output(version, path),
        Language::Java => java_output(version, path),
        Language::CSharp => csharp_output(version, path),
        Language::Python => python_output(version, path),
    }
}
