use crate::version::Version;
use crate::bump::{BumpError, PrintType};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Copy)]
pub enum Language {
    C,
    Go,
    Java,
    CSharp,
    Python,
}

impl Language {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "c" => Some(Language::C),
            "go" => Some(Language::Go),
            "java" => Some(Language::Java),
            "csharp" => Some(Language::CSharp),
            "python" => Some(Language::Python),
            _ => None,
        }
    }

    fn file_description(self) -> &'static str {
        match self {
            Language::C => "C header file",
            Language::Go => "Go source file",
            Language::Java => "Java source file",
            Language::CSharp => "C# source file",
            Language::Python => "Python source file",
        }
    }

}

fn write_output(lang: Language, path: &Path, content: String) -> Result<(), BumpError> {
    fs::write(path, content).map_err(BumpError::IoError)?;
    println!("{} written to {}", lang.file_description(), path.display());
    Ok(())
}

fn c_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let content = match version.version._type.as_str() {
        "calver" => {
            format!(
                r#"/** This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

#ifndef BUMP_VERSION_H
#define BUMP_VERSION_H

#define VERSION_STRING "{}"
#define VERSION_TIMESTAMP "{}"

#endif /* BUMP_VERSION_H */
"#,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        "semver" => {
            format!(
                r#"/** This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

#ifndef BUMP_VERSION_H
#define BUMP_VERSION_H

#define VERSION_PREFIX "{}"
#define VERSION_MAJOR {}
#define VERSION_MINOR {}
#define VERSION_PATCH {}
#define VERSION_PHASE "{}"
#define VERSION_STRING "{}"
#define VERSION_TIMESTAMP "{}"

#endif /* BUMP_VERSION_H */
"#,
                version.version.prefix,
                version.version.major,
                version.version.minor.unwrap_or(0),
                version.version.patch.unwrap_or(0),
                version.phase.name,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        _ => {
            return Err(BumpError::LogicError(format!(
                "Unsupported version type for C output: {}",
                version.version._type
            )));
        }
    };

    write_output(Language::C, path, content)
}

fn go_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let content = match version.version._type.as_str() {
        "calver" => {
            format!(
                r#"// This file is generated by:
//  ____  __  __  __  __  ____ 
// (  _ \(  )(  )(  \/  )(  _ \
//  ) _ < )(__)(  )    (  )___/
// (____/(______)(_/\/\_)(__)  
//
// https://github.com/launchfirestorm/bump

package version

const (
	STRING = "{}"
    TIMESTAMP = "{}"
)
"#,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        "semver" => {
            format!(
                r#"// This file is generated by:
//  ____  __  __  __  __  ____ 
// (  _ \(  )(  )(  \/  )(  _ \
//  ) _ < )(__)(  )    (  )___/
// (____/(______)(_/\/\_)(__)  
//
// https://github.com/launchfirestorm/bump

package version

const (
	PREFIX    = "{}"
	MAJOR     = {}
	MINOR     = {}
	PATCH     = {}
	PHASE     = "{}"
	STRING    = "{}"
    TIMESTAMP = "{}"
)
"#,
                version.version.prefix,
                version.version.major,
                version.version.minor.unwrap_or(0),
                version.version.patch.unwrap_or(0),
                version.phase.name,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last,
            )
        }
        _ => {
            return Err(BumpError::LogicError(format!(
                "Unsupported version type for Go output: {}",
                version.version._type
            )));
        }
    };

    write_output(Language::Go, path, content)
}

fn java_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let content = match version.version._type.as_str() {
        "calver" => {
            format!(
                r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public class Version {{
    public static final String STRING = "{}";
    public static final String TIMESTAMP = "{}";
}}
"#,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        "semver" => {
            format!(
                r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public class Version {{
    public static final String PREFIX = "{}";
    public static final int MAJOR = {};
    public static final int MINOR = {};
    public static final int PATCH = {};
    public static final String PHASE = "{}";
    public static final String STRING = "{}";
    public static final String TIMESTAMP = "{}";
}}
"#,
                version.version.prefix,
                version.version.major,
                version.version.minor.unwrap_or(0),
                version.version.patch.unwrap_or(0),
                version.phase.name,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        _ => {
            return Err(BumpError::LogicError(format!(
                "Unsupported version type for Java output: {}",
                version.version._type
            )));
        }
    };

    write_output(Language::Java, path, content)
}

fn csharp_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let content = match version.version._type.as_str() {
        "calver" => {
            format!(
                r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public static class Version {{
    public const string STRING = "{}";
    public const string TIMESTAMP = "{}";
}}
"#,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        "semver" => {
            format!(
                r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/launchfirestorm/bump
 */

public static class Version {{
    public const string PREFIX = "{}";
    public const int MAJOR = {};
    public const int MINOR = {};
    public const int PATCH = {};
    public const string PHASE = "{}";
    public const string STRING = "{}";
    public const string TIMESTAMP = "{}";
}}
"#,
                version.version.prefix,
                version.version.major,
                version.version.minor.unwrap_or(0),
                version.version.patch.unwrap_or(0),
                version.phase.name,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        _ => {
            return Err(BumpError::LogicError(format!(
                "Unsupported version type for C# output: {}",
                version.version._type
            )));
        }
    };

    write_output(Language::CSharp, path, content)
}

fn python_output(
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    let content = match version.version._type.as_str() {
        "calver" => {
            format!(
                r#"# This file is generated by:
 #  ____  __  __  __  __  ____ 
 # (  _ \(  )(  )(  \/  )(  _ \
 #  ) _ < )(__)(  )    (  )___/
 # (____/(______)(_/\/\_)(__)  
 #
 # https://github.com/launchfirestorm/bump
 #/

VERSION_STRING = "{}"
VERSION_TIMESTAMP = "{}"
"#,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        "semver" => {
            format!(
                r#"# This file is generated by:
 #  ____  __  __  __  __  ____ 
 # (  _ \(  )(  )(  \/  )(  _ \
 #  ) _ < )(__)(  )    (  )___/
 # (____/(______)(_/\/\_)(__)  
 #
 # https://github.com/launchfirestorm/bump
 #/

VERSION_PREFIX = "{}"
VERSION_MAJOR = {}
VERSION_MINOR = {}
VERSION_PATCH = {}
VERSION_CANDIDATE = {}
VERSION_STRING = "{}"
VERSION_TIMESTAMP = "{}"
"#,
                version.version.prefix,
                version.version.major,
                version.version.minor.unwrap_or(0),
                version.version.patch.unwrap_or(0),
                version.phase.name,
                version.to_string(&PrintType::Regular)?,
                version.timestamp.last
            )
        }
        _ => {
            return Err(BumpError::LogicError(format!(
                "Unsupported version type for Python output: {}",
                version.version._type
            )));
        }
    };

    write_output(Language::Python, path, content)
}


pub fn output_file(
    lang: &Language,
    version: &Version,
    path: &Path,
) -> Result<(), BumpError> {
    match lang {
        Language::C => c_output(version, path),
        Language::Go => go_output(version, path),
        Language::Java => java_output(version, path),
        Language::CSharp => csharp_output(version, path),
        Language::Python => python_output(version, path),
    }
}
