name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --release
    
    - name: Run tests
      run: cargo test --release
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bump-binary
        path: target/release/bump
        if-no-files-found: error

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: bump-binary
        path: ./release
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/bump
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.FSTORM_PRIVATE_ACCESS_TOKEN }}
    
    # - name: Set up Cargo
    #   uses: actions-rs/toolchain@v1
    #   with:
    #     toolchain: stable
    #     override: true
    
    # - name: Publish to crates.io
    #   uses: katyo/publish-crates@v2
    #   with:
    #     registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    #     args: --no-verify
