name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    
    steps:
    - uses: actions/checkout@v4

    - name: Install cross-compilation tools for arm
      run: |
        apk add --no-cache binutils-aarch64
        rustup target add aarch64-unknown-linux-musl

    - name: Build && Test
      run: |
        cargo build --release --target x86_64-unknown-linux-musl
        cargo build --release --target aarch64-unknown-linux-musl
        cargo test --release --target x86_64-unknown-linux-musl
        cargo test --release --target aarch64-unknown-linux-musl

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bump-binary
        path: |
          target/x86_64-unknown-linux-musl/release/bump
          target/aarch64-unknown-linux-musl/release/bump
        if-no-files-found: error

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: bump-binary
        path: ./target
        
    - name: Rename binary for release
      run: |
        mv ./target/aarch64-unknown-linux-musl/release/bump bump-linux-musl-arm64
        mv ./target/x86_64-unknown-linux-musl/release/bump bump-linux-musl-amd64

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bump-linux-musl-arm64
          bump-linux-musl-amd64
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.FSTORM_PRIVATE_ACCESS_TOKEN }}
    