name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name_suffix: linux-amd64
            cross_compile: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            name_suffix: linux-arm64
            cross_compile: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name_suffix: windows-amd64
            cross_compile: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            name_suffix: windows-arm64
            cross_compile: true
          - os: macos-latest
            target: x86_64-apple-darwin
            name_suffix: macos-amd64
            cross_compile: false
          - os: macos-latest
            target: aarch64-apple-darwin
            name_suffix: macos-arm64
            cross_compile: true

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Test (skip cross-compiled targets for now)
      if: matrix.cross_compile == false
      run: cargo test --release --target ${{ matrix.target }}

    - name: Prepare binary for upload
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          cp target/${{ matrix.target }}/release/bump.exe bump-${{ matrix.name_suffix }}.exe
        else
          cp target/${{ matrix.target }}/release/bump bump-${{ matrix.name_suffix }}
        fi

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bump-${{ matrix.name_suffix }}
        path: bump-${{ matrix.name_suffix }}*
        if-no-files-found: error

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        
    - name: Prepare release files
      run: |
        mkdir -p ./release
        find ./artifacts -name "bump-*" -type f -exec cp {} ./release/ \;
        ls -la ./release/

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}