name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build && Test
      run: |
        rustup target add x86_64-unknown-linux-musl
        cargo build --release
        cargo test --release
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bump-binary
        path: target/x86_64-unknown-linux-musl/release/bump
        if-no-files-found: error

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: bump-binary
        path: ./release
        
    - name: Rename binary for release
      run: |
        chmod +x ./release/bump
        mv ./release/bump ./release/bump-linux-musl-amd64
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/bump-linux-musl-amd64
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.FSTORM_PRIVATE_ACCESS_TOKEN }}
    